#!/bin/bash
################################################################################
# Library: wsl-backup-readme.sh
################################################################################
# PURPOSE: README generation for WSL backup system
# PLATFORM: Linux (WSL)
################################################################################

# Function: generate_readme
# Description: Creates the README.md file in the backup directory
# Parameters:
#   $1 - Backup directory path where README.md will be created
# Returns: 0 on success, 1 on failure
generate_readme() {
    local backup_dir="$1"

    cat > "$backup_dir/README.md" << README_EOF
# WSL Configuration Backup

**Backup Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Hostname:** $(hostname)
**User:** $USER
**Distribution:** $(lsb_release -d 2>/dev/null | cut -f2- || echo "Unknown")

## Contents

### System Configuration
- \`/etc/wsl.conf\` - WSL configuration
- \`/etc/sudoers\` and \`/etc/sudoers.d/\` - Sudo permissions
- \`/etc/hosts\`, \`/etc/fstab\`, \`/etc/hostname\`
- Network and environment settings

### User Configuration
- Shell configurations (.bashrc, .zshrc, .profile, etc.)
- Git configuration (.gitconfig, .gitignore_global)
- SSH configuration (config, known_hosts)
- Editor configurations (vim, neovim, tmux)

### Development Environment
- NVM, rbenv, Python, Rust, Docker configurations
- Default package lists and versions

### Package Lists
- APT/dpkg packages
- Snap, Flatpak, Homebrew packages
- npm, pip, cargo global packages

### System Information
- Distribution and kernel info
- Environment variables
- PATH configuration

## Restoration

To restore configurations, run:

\`\`\`bash
./restore.sh
\`\`\`

The restoration script provides a menu-driven interface to selectively restore:
1. All configurations (full restore)
2. System configurations
3. Shell configurations
4. Git configuration
5. SSH configuration
6. Vim/Neovim configuration
7. Development environment configs
8. View package lists
9. View system information

**Important Notes:**
- Existing files are automatically backed up before restoration
- System file restoration requires sudo privileges
- SSH keys are NOT backed up for security reasons
- Package lists are for reference - reinstall manually as needed
- You may need to restart WSL after restoring system configurations

## Manual Package Reinstallation

Package lists are saved in the \`packages/\` directory. Use these to reinstall:

**APT packages:**
\`\`\`bash
# Review the list first
less packages/apt-packages.txt

# Install specific packages
sudo apt install <package-name>
\`\`\`

**npm global packages:**
\`\`\`bash
# Install from list
cat packages/npm-global-packages.txt | grep -v '^[├└│]' | cut -d@ -f1 | xargs npm install -g
\`\`\`

**pip packages:**
\`\`\`bash
pip3 install -r packages/pip3-packages.txt
\`\`\`

**Homebrew packages:**
\`\`\`bash
cat packages/brew-packages.txt | xargs brew install
\`\`\`

## Security Considerations

- This backup does NOT include SSH private keys
- Review sudoers files before restoring
- Sensitive credentials should be backed up separately
- Store this backup in a secure location

## Support

For issues or questions, refer to the backup script documentation.

---
Generated by backup-wsl-config.sh
README_EOF

    return 0
}

